name: continuous-integration

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  DOCKER: ""

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
          - macos-latest
    concurrency:
      cancel-in-progress: true
      group: ${{ github.workflow }}-build-${{ github.event.pull_request.number || github.ref }}-${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      - run: cargo build
  lint:
    runs-on: ubuntu-latest
    concurrency:
      cancel-in-progress: true
      group: ${{ github.workflow }}-lint-${{ github.event.pull_request.number || github.ref }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with: 
          toolchain: stable
          components: clippy
      - run: cargo clippy --all --all-targets --all-features -- -D warnings
      - uses: taiki-e/install-action@v2 # don't use taiki-e/cache-cargo-install-action, compiled version already available (https://github.com/taiki-e/install-action/blob/main/TOOLS.md)
        with:
          tool: cargo-machete
      - run: cargo machete
  test:
    if: false # no test so far
    runs-on: ubuntu-latest
    concurrency:
      cancel-in-progress: true
      group: ${{ github.workflow }}-test-${{ github.event.pull_request.number || github.ref }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: taiki-e/install-action@v2 # don't use taiki-e/cache-cargo-install-action, compiled version already available (https://github.com/taiki-e/install-action/blob/main/TOOLS.md)
        with:
          tool: cargo-expand
      - run: cargo test
  fmt:
    runs-on: ubuntu-latest
    concurrency:
      cancel-in-progress: true
      group: ${{ github.workflow }}-fmt-${{ github.event.pull_request.number || github.ref }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with: 
          toolchain: stable
          components: rustfmt
      - run: cargo fmt --all
      - uses: taiki-e/install-action@v2 # don't use taiki-e/cache-cargo-install-action, compiled version already available (https://github.com/taiki-e/install-action/blob/main/TOOLS.md)
        with:
          tool: taplo-cli@0.9.3
      - name: Run cargo sort
        run : taplo format
      - name: Check for a diff
        run: git diff --exit-code
  cargo-deny-checks:
    runs-on: ubuntu-latest
    concurrency:
      cancel-in-progress: true
      group: ${{ github.workflow }}-cargo-deny-checks-${{ github.event.pull_request.number || github.ref }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with: 
          toolchain: stable
      - uses: taiki-e/install-action@v2 # don't use taiki-e/cache-cargo-install-action, compiled version already available (https://github.com/taiki-e/install-action/blob/main/TOOLS.md)
        with:
          tool: cargo-deny
      - name: cargo deny
        run: cargo deny -L error --workspace check bans advisories sources
